spring.application.name=financeapp
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/finance_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=shivam1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN